"""coach phase 2: user files and scheduled jobs tables

Revision ID: 6742cfeac15b
Revises: 8fcd0c3ff903
Create Date: 2026-04-25 11:07:54.026810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6742cfeac15b'
down_revision: Union[str, None] = '8fcd0c3ff903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_scheduled_jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fire_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_coach_scheduled_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_coach_scheduled_jobs'))
    )
    op.create_index('idx_coach_jobs_pending', 'coach_scheduled_jobs', ['fire_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('idx_coach_jobs_user', 'coach_scheduled_jobs', ['user_id'], unique=False)
    op.create_table('coach_user_files',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_coach_user_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'filename', name=op.f('pk_coach_user_files'))
    )
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index(op.f('idx_chat_sessions_roleplay_id'), table_name='chat_sessions', postgresql_where='(roleplay_id IS NOT NULL)')
    op.drop_index(op.f('idx_chat_sessions_unique_user_open_ended'), table_name='chat_sessions', postgresql_where='((user_id IS NOT NULL) AND (module_id IS NULL) AND (roleplay_id IS NULL) AND (archived_at IS NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_chat_sessions_unique_user_open_ended'), 'chat_sessions', ['user_id'], unique=True, postgresql_where='((user_id IS NOT NULL) AND (module_id IS NULL) AND (roleplay_id IS NULL) AND (archived_at IS NULL))')
    op.create_index(op.f('idx_chat_sessions_roleplay_id'), 'chat_sessions', ['roleplay_id'], unique=False, postgresql_where='(roleplay_id IS NOT NULL)')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('coach_user_files')
    op.drop_index('idx_coach_jobs_user', table_name='coach_scheduled_jobs')
    op.drop_index('idx_coach_jobs_pending', table_name='coach_scheduled_jobs', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('coach_scheduled_jobs')
    # ### end Alembic commands ###
